orbs:
  ssh-deployment: arturgontijo/ssh-deployment@dev:0.0.1

jobs:
  i3d-video-action-recognition:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet
    environment:
        SERVICE_NAME: "i3d-video-action-recognition"
        GIT_USER: "singnet"
        GIT_REPO: "dnn-model-services"
        GIT_BRANCH: "master"
    steps:
      - checkout
      - ssh-deployment/deploy:
          ssh-host: ${SSH_HOST}
          ssh-user: ${SSH_USER}
          git-repo: ${GIT_REPO}
          git-branch: ${GIT_BRANCH}
          mainnet-port: "7005"
          testnet-port: "7055"
          run-command: "python3 run_video_action_recon_service.py --ssl"
          test-command: "sleep 20;python3 test_video_action_recon_service.py auto"
          docker-file-url: "https://raw.githubusercontent.com/${GIT_USER}/${GIT_REPO}/${GIT_BRANCH}/services/${SERVICE_NAME}/Dockerfile"
          docker-no-cache: true
          docker-image: "my_i3d_new_ci"
          docker-container: "MY_I3D_CONTAINER"
          docker-nvidia: true
          docker-volume: true
          docker-vol-src: "singnet/.certs"
          docker-vol-dst: "/opt/singnet/.certs"
          infura-api-key: ${INFURA_API_KEY}
          daemon-pk: ${PK_I3D_VIDEO_ACTION_RECON}

workflows:
    version: 2.1
    deploy_application:
        jobs:
            - i3d-video-action-recognition

version: 2.1
