commands:
  ssh-deployment:
    description: |
      Creates an application.
    parameters:
      ssh-host:
        description: The remote SSH server.
        type: string
      ssh-user:
        description: The remote SSH username.
        type: string
      docker-image:
        description: The name of the Docker images that will be built.
        type: string
      docker-container:
        description: The name of the Docker container that will be started.
        type: string
      docker-nvidia:
        description: Starts the container with "--runtime=nvidia".
        type: boolean
        default: false
      docker-volume:
        description: Starts the container with volume map (-v).
        type: boolean
        default: false
      docker-vol-src:
        description: Directory source outside the container.
        type: string
      docker-vol-dst:
        description: Mount destination inside the container.
        type: string
      extras:
        default: ""
        description: Extra arguments.
        type: string
    steps:
      - run:
          name: Getting the remove server Docker version (testing)
          command: |
            export SSH_USER=<< parameters.ssh-host >>
            export SSH_HOST=<< parameters.ssh-user >>
            export DOCKER_IMAGE_NAME=<< parameters.docker-image >>
            export DOCKER_CONTAINER_NAME=<< parameters.docker-container >>
            echo "Testing..."
            ssh -o "StrictHostKeyChecking no" ${SSH_USER}@${SSH_HOST} \<< EOF
              docker version
            EOF

description: |
  Orb to ease the creation and deployment on a remote server using SSH.
display:
  home_url: https://github.com/arturgontijo
  source_url: https://github.com/arturgontijo
examples:
  deploy_application:
    description: |
      Example of deployment using the orb.
    usage:
      orbs:
        ssh-deployment: arturgontijo/ssh-deployment@0.0.1
      version: 2.1
      workflows:
        deploy_application:
          jobs:
          - ssh-deployment/deploy:
              ssh-host: "localhost"
              ssh-user: "ubuntu"
              extras: "ls -shla"

jobs:
  deploy:
    description: Deploy a Docker image from a Github repository on a remote server using SSH.
    docker:
      - image: circleci/python:3.6.6-node
    parameters:
      ssh-host:
        description: The remote SSH server.
        type: string
      ssh-user:
        description: The remote SSH username.
        type: string
      docker-image:
        description: The name of the Docker images that will be built.
        type: string
      docker-container:
        description: The name of the Docker container that will be started.
        type: string
      docker-nvidia:
        description: Starts the container with "--runtime=nvidia".
        type: boolean
        default: false
      docker-volume:
        description: Starts the container with volume map (-v).
        type: boolean
        default: false
      docker-vol-src:
        description: Source directory outside the container.
        type: string
      docker-vol-dst:
        description: Destination directory inside the container.
        type: string
      extras:
        default: ""
        description: Extra arguments.
        type: string
    steps:
    - checkout
    - ssh-deployment:
        ssh-host: << parameters.ssh-host >>
        ssh-user: << parameters.ssh-user >>
        docker-image: << parameters.docker-image >>
        docker-container: << parameters.docker-container >>
        docker-nvidia: << parameters.docker-nvidia >>
        docker-volume: << parameters.docker-volume >>
        docker-vol-src: << parameters.docker-vol-src >>
        docker-vol-dst: << parameters.docker-vol-dst >>
        extras: << parameters.extras >>

version: 2.1
